name: AutoAmpDL build

on:
  workflow_dispatch:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - run: pip install pyinstaller
      - run: pyinstaller --name "AutoAmpDL" --clean --onefile main.py